### ISSUE TITLE
感谢作者开源，有几个问题想请教下！

### ISSUE THREAD

**Issue by bingdu0** [JiangHaiYang01/Moya#1]
首先感谢作者开源，框架很优秀，我在使用的过程中，遇到3个问题，想请教下大牛：
1.对于失败重试，重试的次数和间隔时间怎么处理？
2.能否加一下Https的支持。
3.串行 请求和并行请求能否在demo中实现一下。

**Comment by JiangHaiYang01** [comment]
针对问题1：
对于失败重试，重试的次数和间隔时间怎么处理 本质上moya 内部还是使用retrofit ,retrofit内部使用的okhttp3. 在失败重试的过程中。是依赖okhttp3的重试机制。更加详细的重试逻辑可以参考 okhttp 的 RetryAndFollowUpInterceptor 拦截器。这个是处理重试的。失败了并且满足可以重试的条件就重试。不会等待的。想一下就能理解。都要重试了。干嘛还等一会在重试呢

问题2
能否加一下Https的支持，本身的Retrofit 就是支持https的。笔者后续会将其api 以及事例也更新。

问题3
关于并行与串行。个人认为，不属于网络框架的范畴。可以在外部去实现。在大神郭嫂的开源作品中，也能发现。相应的做减法。而不是想更多的东西加入到库当中。笔者会在后续完善这个框架。

最后
感谢问题的反馈。这边我也会积极的配合修该DEMO.以及拓展用法。此项目目前没有真正的开源出去。而是还在拓展功能。后续的改动，暂时不得知。

未来的计划
1.将Rxjava3加上
2.支持下载和上传的优先级队列
3.对于更加配置拓展

最近事情比较多。笔者也在找工作当中。更多的精力还是在其他方面。最后再次感谢反馈问题。会积极的处理
